# Generated by Django 4.0.3 on 2023-12-29 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0019_alter_doctor_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='department',
            new_name='blood_group_choices',
        ),
    ]
