# Generated by Django 4.0.3 on 2023-12-29 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0021_rename_admitdate_patient_dob_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='qrCode',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='profile_pic/PatientsQrCodes/'),
        ),
    ]
