# Generated by Django 4.0.3 on 2023-12-29 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0022_patient_qrcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='qrCode',
        ),
    ]
