# Generated by Django 4.0.3 on 2024-01-03 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0024_patient_qrcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='qrCode',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='generated_QRs/'),
        ),
    ]
