# Generated by Django 4.0.3 on 2024-01-28 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0027_appointment_id_alter_appointment_patientid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='department',
            field=models.CharField(choices=[('Labour', 'Labour'), ('Self-employed', 'Self-employed'), ('Service', 'Service'), ('Corporate', 'Corporate'), ('Government/Public Sector', 'Government/Public Sector'), ('Nonprofit/Volunteer Work', 'Nonprofit/Volunteer Work')], default='Corporate', max_length=50),
        ),
    ]
