# Generated by Django 4.0.3 on 2024-01-28 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0029_alter_doctor_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='work_department',
            field=models.CharField(choices=[('Labour', 'Labour'), ('Self-employed', 'Self-employed'), ('Service', 'Service'), ('Corporate', 'Corporate'), ('Government/Public Sector', 'Government/Public Sector'), ('Nonprofit/Volunteer Work', 'Nonprofit/Volunteer Work')], default='Corporate', max_length=50),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='department',
            field=models.CharField(choices=[('Cardiologist', 'Cardiologist'), ('Dermatologists', 'Dermatologists'), ('Emergency Medicine Specialists', 'Emergency Medicine Specialists'), ('Allergists/Immunologists', 'Allergists/Immunologists'), ('Anesthesiologists', 'Anesthesiologists'), ('Colon and Rectal Surgeons', 'Colon and Rectal Surgeons')], default='Cardiologist', max_length=50),
        ),
    ]
