# Generated by Django 4.0.3 on 2024-01-28 08:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0031_appointment_appointmenttime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointmentTime',
            field=models.TimeField(default=datetime.time(8, 28, 21, 433527)),
        ),
    ]
