# Generated by Django 4.0.3 on 2024-01-28 08:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0033_alter_appointment_appointmenttime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointmentTime',
            field=models.TimeField(default=datetime.time(8, 40, 52, 885585)),
        ),
    ]
