# Generated by Django 4.0.3 on 2024-01-28 19:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0034_alter_appointment_appointmenttime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointmentTime',
            field=models.TimeField(default=datetime.time(19, 58, 50, 97401)),
        ),
        migrations.AlterField(
            model_name='patient',
            name='assignedDoctorId',
            field=models.PositiveIntegerField(default=14, null=True),
        ),
    ]
