# Generated by Django 4.0.3 on 2024-02-01 18:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0036_alter_appointment_appointmentdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointmentTime',
            field=models.TimeField(default=datetime.time(18, 46, 12, 766116)),
        ),
    ]   
